# Generated by Django 4.0.5 on 2026-02-10 04:10

import backend_api.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_access_role', models.CharField(max_length=255)),
                ('name_of_role', models.CharField(default='role_name', max_length=255)),
            ],
            options={
                'db_table': 'access_roles',
            },
        ),
        migrations.CreateModel(
            name='AcsParttimerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parttimerName', models.CharField(max_length=100)),
                ('parttimerId', models.CharField(max_length=100)),
                ('studentName', models.CharField(max_length=100)),
                ('studentId', models.CharField(max_length=100)),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2026, 2, 10))])),
                ('applicationsAppliedSearched', models.IntegerField(default=0)),
                ('applicationsAppliedSaved', models.IntegerField(default=0)),
                ('easyApply', models.IntegerField(default=0)),
                ('recruiterDirectMessages', models.CharField(blank=True, max_length=200, null=True)),
                ('connectMessages', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'PartTimer_status',
            },
        ),
        migrations.CreateModel(
            name='CollegesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('international_UG_link', models.URLField(blank=True, null=True)),
                ('international_graduation_link', models.URLField(blank=True, null=True)),
                ('application_UG_link', models.URLField(blank=True, null=True)),
                ('application_graduation_link', models.URLField(blank=True, null=True)),
                ('application_UG_fee', models.TextField(blank=True, null=True)),
                ('application_UG_fee_link', models.URLField(blank=True, null=True)),
                ('application_graduation_fee', models.TextField(blank=True, null=True)),
                ('application_graduation_fee_link', models.URLField(blank=True, null=True)),
                ('gre_score', models.TextField(blank=True, null=True)),
                ('gre_score_link', models.URLField(blank=True, null=True)),
                ('toefl_UG_score', models.TextField(blank=True, null=True)),
                ('toefl_UG_score_link', models.URLField(blank=True, null=True)),
                ('toefl_graduation_score', models.TextField(blank=True, null=True)),
                ('toefl_graduation_score_link', models.URLField(blank=True, null=True)),
                ('ielts_ug_score', models.TextField(blank=True, null=True)),
                ('ielts_ug_score_link', models.URLField(blank=True, null=True)),
                ('ielts_graduation_score', models.TextField(blank=True, null=True)),
                ('ielts_graduation_score_link', models.URLField(blank=True, null=True)),
                ('fall_deadline_UG', models.TextField(blank=True, null=True)),
                ('fall_deadline_UG_link', models.URLField(blank=True, null=True)),
                ('fall_deadline_graduation', models.TextField(blank=True, null=True)),
                ('fall_deadline_graduation_link', models.URLField(blank=True, null=True)),
                ('spring_deadline_UG', models.TextField(blank=True, null=True)),
                ('spring_deadline_UG_link', models.URLField(blank=True, null=True)),
                ('spring_deadline_graduation', models.TextField(blank=True, null=True)),
                ('spring_deadline_graduation_link', models.URLField(blank=True, null=True)),
                ('college_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('college_email_link', models.URLField(blank=True, null=True)),
                ('college_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('college_phone_link', models.URLField(blank=True, null=True)),
                ('international_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('international_person_email_link', models.URLField(blank=True, null=True)),
                ('public_private', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10, null=True)),
                ('UG_courses', models.TextField(blank=True, null=True)),
                ('UG_courses_link', models.URLField(blank=True, null=True)),
                ('graduation_courses', models.TextField(blank=True, null=True)),
                ('graduation_courses_link', models.URLField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'collegelist',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('visa_status', models.CharField(choices=[('OPT', 'OPT'), ('CPT', 'CPT'), ('H1B', 'H1B'), ('H4 EAD', 'H4 EAD')], max_length=20)),
                ('visa_status_verified', models.BooleanField(default=False)),
                ('visa_validity', models.DateField()),
                ('visa_validity_verified', models.BooleanField(default=False)),
                ('btech_college', models.CharField(blank=True, max_length=100, null=True)),
                ('btech_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('btech_graduation_date', models.DateField(blank=True, null=True)),
                ('masters_college', models.CharField(blank=True, max_length=100, null=True)),
                ('masters_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('masters_graduation_date', models.DateField(blank=True, null=True)),
                ('technologies', models.JSONField()),
                ('current_location', models.CharField(max_length=100)),
                ('relocation', models.BooleanField()),
                ('experience_in_us', models.TextField()),
                ('experience_in_us_verified', models.BooleanField(default=False)),
                ('experience_in_india', models.TextField()),
                ('experience_in_india_verified', models.BooleanField(default=False)),
                ('relocation_preference', models.TextField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_number_verified', models.BooleanField(default=False)),
                ('driving_licence', models.CharField(blank=True, max_length=50)),
                ('rate_expectations', models.CharField(blank=True, max_length=100, null=True)),
                ('last_4_ssn', models.CharField(blank=True, max_length=4, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('linkedin_url_verified', models.BooleanField(default=False)),
                ('uploaded_date', models.DateField(default=django.utils.timezone.localdate)),
                ('original_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('consulting_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
            options={
                'db_table': 'consultant_details',
            },
        ),
        migrations.CreateModel(
            name='DeviceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('about_device', models.TextField(blank=True)),
                ('allocated_to', models.CharField(max_length=100)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_allocation',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'employer_details',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('includes', models.JSONField(default=list)),
                ('excludes', models.JSONField(default=list)),
                ('package_for', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PartTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('answered_questions', models.BooleanField(default=False)),
                ('current_occupation', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'PartTimer',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('employer', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'recrutier_details',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='ShopingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('link', models.URLField()),
                ('age_group', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ShopingProduct',
            },
        ),
        migrations.CreateModel(
            name='StatusUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('subsidary', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, validators=[django.core.validators.MaxValueValidator(backend_api.models.current_date)])),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('studentName', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsappId', models.CharField(blank=True, max_length=100, null=True)),
                ('applicationsAppliedSearched', models.IntegerField(blank=True, default=0, null=True)),
                ('applicationsAppliedSaved', models.IntegerField(blank=True, default=0, null=True)),
                ('easyApply', models.IntegerField(blank=True, default=0, null=True)),
                ('recruiterDirectMessages', models.CharField(blank=True, max_length=200, null=True)),
                ('connectMessages', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('ticket_link', models.CharField(blank=True, max_length=100, null=True)),
                ('github_link', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('total_current_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('distance_travelled', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('whatsapp_group_number', models.CharField(blank=True, max_length=15, null=True)),
                ('leave', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'Status_updates',
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subsidiaryName', models.CharField(max_length=255)),
                ('subName', models.CharField(max_length=255)),
                ('parttimer_multi_status', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subsidiary',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_time_from', models.DateField(null=True)),
                ('work_time_to', models.DateField(null=True)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='team_members/')),
                ('facebook_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('subsidiary', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('enrolled_services', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('consultant_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_api.consultant')),
                ('employer_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_api.employer')),
                ('recruiter_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_api.recruiter')),
            ],
            options={
                'db_table': 'status_consultant',
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='employer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_employers', to='backend_api.employer'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='recruiter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_recruiters', to='backend_api.recruiter'),
        ),
        migrations.CreateModel(
            name='CollegeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.collegeslist')),
            ],
            options={
                'db_table': 'social_links',
            },
        ),
        migrations.CreateModel(
            name='HappinessIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness_score', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.user')),
            ],
            options={
                'db_table': 'happiness_index',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
