# Generated by Django 5.0.1 on 2024-01-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegesList',
        ),
    ]
