# Generated by Django 4.0.5 on 2023-12-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('referred_by', models.CharField(blank=True, max_length=255, null=True)),
                ('current_occupation', models.CharField(max_length=255)),
                ('is_student', models.BooleanField(default=False)),
                ('course_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('current_pursuing_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
