# Generated by Django 4.0.5 on 2023-12-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_collegeslist_parttimer_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_access_role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'access_roles',
            },
        ),
    ]
