# Generated by Django 5.0.1 on 2024-01-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_collegeslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeslist',
            name='application_UG_fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegeslist',
            name='application_graduation_fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegeslist',
            name='gre_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegeslist',
            name='ielts_graduation_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegeslist',
            name='ielts_ug_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegeslist',
            name='toefl_UG_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegeslist',
            name='toefl_graduation_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
