# Generated by Django 4.0.5 on 2023-12-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_accessroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessroles',
            name='name_of_role',
            field=models.CharField(default='role_name', max_length=255),
        ),
    ]
