# Generated by Django 4.0.5 on 2024-01-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_accessroles_name_of_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeslist',
            name='UG_courses_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='application_UG_fee_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='application_graduation_fee_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='college_email_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='college_phone_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='fall_deadline_UG_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='fall_deadline_graduation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='graduation_courses_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='gre_score_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='ielts_graduation_score_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='ielts_ug_score_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='international_person_email_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='spring_deadline_UG_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='spring_deadline_graduation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='toefl_UG_score_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeslist',
            name='toefl_graduation_score_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
