# Generated by Django 4.0.5 on 2023-12-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_consultant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultant',
            table='consultants',
        ),
    ]
