# Generated by Django 5.0.1 on 2024-01-29 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_collegeslist_fall_deadline_ug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttimer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parttimer',
            name='course_of_study',
        ),
        migrations.RemoveField(
            model_name='parttimer',
            name='current_pursuing_year',
        ),
        migrations.RemoveField(
            model_name='parttimer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='parttimer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parttimer',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='parttimer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parttimer',
            name='phone',
        ),
        migrations.AddField(
            model_name='parttimer',
            name='answered_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parttimer',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parttimer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parttimer',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parttimer',
            name='current_occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parttimer',
            name='referred_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='parttimer',
            table='PartTimer',
        ),
    ]
