# Generated by Django 4.0.5 on 2024-01-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_collegeslist_ug_courses_link_and_more'),
        ('backend_api', '0005_consultant'),
    ]

    operations = [
    ]
