# Generated by Django 5.0.1 on 2024-01-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_remove_parttimer_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttimer',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
