# Generated by Django 5.0.1 on 2024-01-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_parttimer_course_name'),
    ]

    operations = [
        # Empty - user_id is already primary key (unique), 
        # so unique_together is redundant and causes duplicate constraint error
    ]
