# Generated by Django 5.0.1 on 2024-01-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_alter_user_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parttimer',
            old_name='user',
            new_name='user_id',
        ),
    ]
