# Generated by Django 5.0.1 on 2024-01-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_rename_user_parttimer_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parttimer',
            old_name='user_id',
            new_name='user',
        ),
    ]
