# Generated by Django 5.0.1 on 2024-01-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_rename_user_id_parttimer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimer',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
