# Generated by Django 5.0.1 on 2024-01-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_alter_parttimer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimer',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
