# Generated by Django 5.0.1 on 2024-01-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_alter_user_enrolled_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimer',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
