# Generated by Django 5.0.1 on 2024-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0016_alter_parttimer_year_of_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('includes', models.JSONField(default=list)),
                ('excludes', models.JSONField(default=list)),
                ('package_for', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
    ]
