# Generated by Django 4.0.5 on 2024-04-29 01:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcsParttimerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parttimerName', models.CharField(max_length=100)),
                ('parttimerId', models.CharField(max_length=20)),
                ('studentName', models.CharField(max_length=100)),
                ('studentId', models.CharField(max_length=20)),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 4, 29))])),
                ('applicationsAppliedSearched', models.IntegerField(default=0)),
                ('applicationsAppliedSaved', models.IntegerField(default=0)),
                ('easyApply', models.IntegerField(default=0)),
                ('recruiterDirectMessages', models.CharField(blank=True, max_length=200, null=True)),
                ('connectMessages', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'PartTimer_status',
            },
        ),
    ]
