# Generated by Django 5.0.6 on 2024-09-23 15:40

import backend_api.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcsParttimerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parttimerName', models.CharField(max_length=100)),
                ('parttimerId', models.CharField(max_length=100)),
                ('studentName', models.CharField(max_length=100)),
                ('studentId', models.CharField(max_length=100)),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 23))])),
                ('applicationsAppliedSearched', models.IntegerField(default=0)),
                ('applicationsAppliedSaved', models.IntegerField(default=0)),
                ('easyApply', models.IntegerField(default=0)),
                ('recruiterDirectMessages', models.CharField(blank=True, max_length=200, null=True)),
                ('connectMessages', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'PartTimer_status',
            },
        ),
        migrations.CreateModel(
            name='ShopingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('link', models.URLField()),
                ('age_group', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': ' ShopingProduct ',
            },
        ),
        migrations.CreateModel(
            name='StatusUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(backend_api.models.current_date)])),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Status_updates',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CollegeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.collegeslist')),
            ],
            options={
                'db_table': 'social_links',
            },
        ),
    ]
