# Generated by Django 4.0.5 on 2024-05-09 01:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_acsparttimerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 9))]),
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='parttimerId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='studentId',
            field=models.CharField(max_length=100),
        ),
    ]
