# Generated by Django 5.0.3 on 2024-09-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_acsparttimerstatus_statusupdates_collegeslist_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('link', models.URLField()),
                ('age_group', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ShopingProduct',
            },
        ),
    ]
