# Generated by Django 5.0.6 on 2024-10-02 15:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0019_shopingproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='shopingproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 10, 2))]),
        ),
    ]
