# Generated by Django 4.0.5 on 2024-06-02 11:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0022_alter_acsparttimerstatus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 6, 2))])),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 6, 2))]),
        ),
    ]
