# Generated by Django 4.0.5 on 2024-06-12 17:30

import backend_api.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0024_alter_statusupdates_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 6, 12))]),
        ),
        migrations.AlterField(
            model_name='statusupdates',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(backend_api.models.current_date)]),
        ),
        migrations.CreateModel(
            name='CollegeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.collegeslist')),
            ],
            options={
                'db_table': 'social_links',
            },
        ),
    ]
