# Generated by Django 4.0.5 on 2024-06-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0025_alter_acsparttimerstatus_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegedetail',
            old_name='college_id',
            new_name='college',
        ),
    ]
