# Generated by Django 4.0.5 on 2024-09-23 13:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0028_alter_acsparttimerstatus_date_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeslist',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 23))]),
        ),
    ]
