# Generated by Django 4.0.5 on 2024-10-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_acsparttimerstatus_shopingproduct_statusupdates_and_more'),
        ('backend_api', '0020_remove_shopingproduct_image_url_shopingproduct_image_and_more'),
        ('backend_api', '0029_collegeslist_state_alter_acsparttimerstatus_date'),
    ]

    operations = [
    ]
