# Generated by Django 4.0.5 on 2024-10-17 17:19

import builtins
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0030_merge_20241017_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'employer_details',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('employer', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'recrutier_details',
            },
        ),
        migrations.RemoveField(
            model_name='shopingproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='shopingproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 10, 17))]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='shopingproduct',
            table='ShopingProduct',
        ),
        migrations.AddField(
            model_name='consultant',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.employer'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.recruiter'),
        ),
    ]
