# Generated by Django 4.0.5 on 2024-11-20 18:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0034_remove_consultant_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='recruiter',
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 11, 20))]),
        ),
    ]
