# Generated by Django 4.0.5 on 2024-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0035_remove_consultant_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='linkedin_url_verified',
            field=models.BooleanField(default=False),
        ),
    ]
