# Generated by Django 4.0.5 on 2024-12-26 10:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0036_teammember_consultant_linkedin_url_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='uploaded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
