# Generated by Django 4.0.5 on 2024-12-31 14:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0038_teammember_alter_acsparttimerstatus_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='uploaded_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='statusconsultant',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
