# Generated by Django 5.0.6 on 2025-02-17 16:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0039_teammember_alter_acsparttimerstatus_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('about_device', models.TextField(blank=True)),
                ('allocated_to', models.CharField(max_length=100)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_allocation',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_time_from', models.DateField(null=True)),
                ('work_time_to', models.DateField(null=True)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='team_members/')),
                ('facebook_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('subsidiary', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 2, 17))]),
        ),
    ]
