# Generated by Django 5.1.7 on 2025-03-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0040_deviceallocation_teammember_and_more'),
        ('backend_api', '0040_teammember_remove_statusupdates_status_and_more'),
    ]

    operations = [
    ]
