# Generated by Django 4.0.5 on 2025-04-14 17:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0042_alter_acsparttimerstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdates',
            name='leave',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 4, 14))]),
        ),
    ]
