# Generated by Django 4.0.5 on 2025-06-26 17:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0045_merged_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subsidiaryName', models.CharField(max_length=255)),
                ('subName', models.CharField(max_length=255)),
                ('parttimer_multi_status', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subsidiary',
            },
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 6, 26))]),
        ),
    ]
