# Generated by Django 4.0.5 on 2025-06-28 08:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0046_subsidiary_alter_acsparttimerstatus_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusupdates',
            old_name='studentId',
            new_name='whatsappId',
        ),
        migrations.AlterField(
            model_name='acsparttimerstatus',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 6, 28))]),
        ),
    ]
