# Generated by Django 5.2 on 2025-05-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crim', models.FloatField()),
                ('zn', models.FloatField()),
                ('indus', models.FloatField()),
                ('chas', models.FloatField()),
                ('nox', models.FloatField()),
                ('rm', models.FloatField()),
                ('age', models.FloatField()),
                ('dis', models.FloatField()),
                ('rad', models.FloatField()),
                ('tax', models.FloatField()),
                ('ptratio', models.FloatField()),
                ('b', models.FloatField()),
                ('lstat', models.FloatField()),
                ('predicted_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
