name: Deploy the backend

on:
    push:
        branches:
            - dev
            - main

env:

    EC2_USER:  ${{ secrets.EC2_USER }}                  # Replace with your EC2 username
    EC2_HOST: ${{ secrets.EC2_HOST }}

jobs:
    build:
        runs-on: ubuntu-latest
        environment: dev
        # permissions:
        #     id-token: write  # Grant id-token permission for OIDC
        #     contents: read 
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            # - name: Setup Python
            #   uses: actions/setup-python@v3
            #   with:
            #     python-version: ${{ matrix.python-version }}
            # - name: Install Dependencies
            #   run: |
            #         python -m pip install --upgrade pip
            #         pip install -r requirements.txt 
            #         pip install awscli

            - name: Configure SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy Code to EC2
              run: |
                echo "Connecting to EC2..."
                ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
                    cd Django_Backend/
                    ls -la
                    git branch
                    git pull origin main
                    docker-compose down
                    docker-compose build
                    docker-compose up -d
                EOF
             

                    
            
                          
                







