name: Deploy the backend

on:
    push:
        branches:
            - dev
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            id-token: write  # Grant id-token permission for OIDC
            contents: read 
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt 
                    pip install awscli

            - name: Configure aws creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::805556599116:role/Devops-githubactions
                aws-region: us-east-1

            - name: check aws creds
              run: |
                echo $AWS_ACCESS_KEY_ID


                    
            
                          
                







