# Generated by Django 4.0.5 on 2026-02-10 04:10

from django.db import migrations, models
import django.utils.timezone
import shortuuid.main
import transaction_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('accountant_name', models.CharField(max_length=100)),
                ('accountant_id', models.CharField(max_length=50)),
                ('credited_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debited_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_datetime', models.DateTimeField()),
                ('uploaded_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=50, validators=[transaction_api.models.validate_transaction_type])),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], max_length=50, validators=[transaction_api.models.validate_payment_type])),
                ('subsidiary', models.CharField(choices=[('AMS', 'AMS'), ('ACS', 'ACS'), ('ASS', 'ASS'), ('APS', 'APS'), ('ATI', 'ATI')], max_length=20, validators=[transaction_api.models.validate_subsidiary])),
                ('currency', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
