# Generated by Django 4.0.5 on 2024-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_id', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_id', models.CharField(max_length=50)),
                ('accountant_name', models.CharField(max_length=100)),
                ('accountant_id', models.CharField(max_length=50)),
                ('credited_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debited_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_datetime', models.DateTimeField()),
                ('uploaded_datetime', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('cash', 'CASH'), ('upi', 'UPI'), ('bank_transfer', 'BANK_TRANSFER')], max_length=50)),
                ('subsidiary', models.CharField(choices=[('AMS', 'AMS'), ('ACS', 'ACS'), ('ASS', 'ASS'), ('APS', 'APS'), ('ATI', 'ATI')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
