# Generated by Django 4.0.5 on 2024-05-16 16:02

from django.db import migrations, models
import transaction_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subsidiary',
            field=models.CharField(max_length=20, validators=[transaction_api.models.validate_subsidiary]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=50, validators=[transaction_api.models.validate_transaction_type]),
        ),
    ]
