# Generated by Django 4.0.5 on 2024-05-16 16:25

from django.db import migrations, models
import transaction_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0003_alter_transaction_subsidiary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subsidiary',
            field=models.CharField(choices=[('AMS', 'AMS'), ('ACS', 'ACS'), ('ASS', 'ASS'), ('APS', 'APS'), ('ATI', 'ATI')], max_length=20, validators=[transaction_api.models.validate_subsidiary]),
        ),
    ]
