# Generated by Django 4.0.5 on 2024-05-19 11:31

from django.db import migrations, models
import transaction_api.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0004_alter_transaction_subsidiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], max_length=50, validators=[transaction_api.models.validate_transaction_type]),
        ),
    ]
