# Generated by Django 4.0.5 on 2024-05-19 12:37

from django.db import migrations, models
import shortuuid.main
import transaction_api.models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0008_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_datetime',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uploaded_datetime',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
