# Generated by Django 4.0.5 on 2024-05-30 15:05

from django.db import migrations, models
import shortuuid.main
import transaction_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0010_alter_transaction_transaction_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], default='credit', max_length=50, validators=[transaction_api.models.validate_payment_type]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=50, validators=[transaction_api.models.validate_transaction_type]),
        ),
    ]
